# Generated by Django 4.2.20 on 2025-04-22 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_proveedor_visible_en_web'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socios', '0005_remove_socio_responsable_stock'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionRecogida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Inicio de Sesión')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de Sesión')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada (Pendiente Validación)'), ('validada', 'Validada'), ('rechazada', 'Rechazada')], default='abierta', max_length=20, verbose_name='Estado')),
                ('notas_validacion', models.TextField(blank=True, help_text='Notas del Gestor de Stock durante la validación.', verbose_name='Notas Validación')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Validación')),
                ('gestor_validacion', models.ForeignKey(blank=True, help_text='Socio Gestor de Stock que validó/rechazó la sesión.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Gestor Validación')),
                ('responsable_registro', models.ForeignKey(help_text='Socio responsable de registrar las retiradas en esta sesión.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Registro')),
            ],
            options={
                'verbose_name': 'Sesión de Recogida',
                'verbose_name_plural': 'Sesiones de Recogida',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RetiradaSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiradas', to='stock.sesionrecogida', verbose_name='Sesión')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas_realizadas', to='socios.socio', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Retirada de Socio',
                'verbose_name_plural': 'Retiradas de Socios',
                'ordering': ['sesion', 'socio__apellido', 'socio__nombre'],
                'unique_together': {('sesion', 'socio')},
            },
        ),
        migrations.CreateModel(
            name='ItemRetirado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad retirada (en unidad_venta del producto)', max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario_momento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario (en retirada)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto')),
                ('retirada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_retirados', to='stock.retiradasocio', verbose_name='Retirada')),
            ],
            options={
                'verbose_name': 'Ítem Retirado',
                'verbose_name_plural': 'Ítems Retirados',
                'unique_together': {('retirada', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='item_retirado_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='stock.itemretirado', verbose_name='Ítem Retirado Origen'),
        ),
    ]
