# Generated by Django 4.2.20 on 2025-04-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0008_remove_movimientocuenta_retirada_origen'),
        ('stock', '0002_sesionrecogida_retiradasocio_itemretirado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='retiradasocio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='retiradasocio',
            name='sesion',
        ),
        migrations.RemoveField(
            model_name='retiradasocio',
            name='socio',
        ),
        migrations.RemoveField(
            model_name='sesionrecogida',
            name='gestor_validacion',
        ),
        migrations.RemoveField(
            model_name='sesionrecogida',
            name='responsable_registro',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='item_retirado_origen',
        ),
        migrations.DeleteModel(
            name='ItemRetirado',
        ),
        migrations.DeleteModel(
            name='RetiradaSocio',
        ),
        migrations.DeleteModel(
            name='SesionRecogida',
        ),
    ]
