# Generated by Django 4.2.20 on 2025-04-22 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_proveedor_visible_en_web'),
        ('socios', '0009_create_stock_manager_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_alter_retiradasocio_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecogidaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha de Recogida')),
                ('procesada', models.BooleanField(default=False, verbose_name='Procesada')),
            ],
            options={
                'verbose_name': 'Recogida Semanal',
                'verbose_name_plural': 'Recogidas Semanales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EntregaSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('procesada', 'Procesada')], default='pendiente', max_length=10)),
                ('recogida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='stock.recogidasemanal')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_registradas', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_recibidas', to='socios.socio')),
            ],
            options={
                'verbose_name': 'Entrega a Socio',
                'verbose_name_plural': 'Entregas a Socios',
                'ordering': ['-recogida__fecha', 'socio__apellido', 'socio__nombre'],
                'unique_together': {('recogida', 'socio')},
            },
        ),
        migrations.CreateModel(
            name='ItemEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('entrega_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.entregasocio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Ítem de Entrega',
                'verbose_name_plural': 'Ítems de Entrega',
                'unique_together': {('entrega_socio', 'producto')},
            },
        ),
    ]
