# Generated by Django 4.2.20 on 2025-04-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_recogidasemanal_entregasocio_itementrega'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itementrega',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itementrega',
            name='entrega_socio',
        ),
        migrations.RemoveField(
            model_name='itementrega',
            name='producto',
        ),
        migrations.DeleteModel(
            name='EntregaSocio',
        ),
        migrations.DeleteModel(
            name='ItemEntrega',
        ),
        migrations.DeleteModel(
            name='RecogidaSemanal',
        ),
    ]
