# Generated by Django 4.2.20 on 2025-05-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0017_remove_socio_puede_crear_comanda_esporadica'),
        ('stock', '0005_alter_itementrega_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCompraStockProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Registro de Compra Stock',
                'verbose_name_plural': 'Registros de Compras Stock',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('socios.registrocomprasocio',),
        ),
    ]
