# Generated by Django 4.2.20 on 2025-06-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_registrocomprastockproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrocomprastockproxy',
            options={'verbose_name': 'Registro de Compra Stock', 'verbose_name_plural': "Registres de Compres d'Estoc"},
        ),
    ]
