# Generated by Django 4.2.20 on 2025-06-02 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocalendario',
            name='color',
            field=models.CharField(default='#007bff', help_text='Código hexadecimal del color (ej. #007bff)', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='eventocalendario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='eventocalendario',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='eventocalendario',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='eventocalendario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='eventocalendario',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
