# Generated by Django 5.1.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_eventocalendario_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='compartir_api',
            field=models.BooleanField(default=False, help_text="Si està marcat, aquest event serà visible a l'API pública per altres cooperatives", verbose_name="Compartir a l'API"),
        ),
    ]