# Generated by Django 5.1.6 on 2025-02-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandaRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=20)),
                ('dia_semana', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='activa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoColectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('semanal', 'Semanal'), ('esporadico', 'Esporádico')], max_length=20)),
                ('estado', models.CharField(default='abierto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeleccionSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seleccion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidocolectivo')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSeleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('seleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.seleccionsocio')),
            ],
        ),
    ]
