# Generated by Django 3.2.21 on 2025-03-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandarecurrente',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria'),
        ),
        migrations.AddField(
            model_name='comandarecurrente',
            name='dia_mes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comandarecurrente',
            name='dia_semana',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
