# Generated by Django 3.2.21 on 2025-03-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20250301_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandarecurrente',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comandarecurrente',
            name='frecuencia',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('esporadico', 'Esporádico')], max_length=20),
        ),
    ]
