# Generated by Django 3.2.21 on 2025-03-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('pedidos', '0003_auto_20250301_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandarecurrente',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.proveedor'),
        ),
    ]
