# Generated by Django 3.2.21 on 2025-03-01 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('pedidos', '0004_comandarecurrente_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocolectivo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria'),
        ),
        migrations.AddField(
            model_name='pedidocolectivo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.proveedor'),
        ),
    ]
