# Generated by Django 3.2.21 on 2025-03-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20250301_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandarecurrente',
            name='ultima_generacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
