# Generated by Django 3.2.21 on 2025-03-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_comandarecurrente_ultima_generacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocolectivo',
            name='tipo',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('esporadico', 'Esporádico'), ('mensual', 'Mensual'), ('quincenal', 'Quincenal')], max_length=20),
        ),
    ]
