# Generated by Django 3.2.21 on 2025-03-15 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_user'),
        ('pedidos', '0007_alter_pedidocolectivo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandarecurrente',
            name='socio_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.socio'),
        ),
    ]
