# Generated by Django 3.2.21 on 2025-03-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_comandarecurrente_socio_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocolectivo',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.comandarecurrente'),
        ),
    ]
