# Generated by Django 3.2.21 on 2025-03-16 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_user'),
        ('pedidos', '0010_pedidocolectivo_socio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandarecurrente',
            name='socio_asignado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='socios.socio'),
            preserve_default=False,
        ),
    ]
