# Generated by Django 3.2.21 on 2025-04-10 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_user'),
        ('pedidos', '0011_alter_comandarecurrente_socio_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandarecurrente',
            name='socio_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.socio'),
        ),
    ]
