# Generated by Django 3.2.21 on 2025-04-11 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0004_producto_es_stock'),
        ('pedidos', '0012_alter_comandarecurrente_socio_asignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacionStockConsumido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad consumida.', max_digits=10)),
                ('fecha_anotacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la anotación.')),
                ('notas', models.TextField(blank=True, null=True)),
                ('anotado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la anotación.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(help_text='Producto de stock consumido.', on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('socio', models.ForeignKey(blank=True, help_text='Socio que retiró el stock.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.socio')),
            ],
            options={
                'ordering': ['-fecha_anotacion'],
            },
        ),
    ]
