# Generated by Django 4.2.20 on 2025-04-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_anotacionstockconsumido'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleseleccion',
            name='cantidad_entregada',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad realmente entregada al socio (puede ser menor si no llega todo el pedido colectivo)', null=True),
        ),
        migrations.AddField(
            model_name='detalleseleccion',
            name='validado_por_gestor',
            field=models.BooleanField(default=False, help_text='Indica si el gestor de la comanda ha validado la cantidad entregada'),
        ),
    ]
