# Generated by Django 4.2.20 on 2025-04-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_detalleseleccion_cantidad_entregada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleseleccion',
            name='cantidad_entregada',
        ),
        migrations.RemoveField(
            model_name='detalleseleccion',
            name='validado_por_gestor',
        ),
    ]
