# Generated by Django 4.2.20 on 2025-04-12 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0015_remove_detalleseleccion_cantidad_entregada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionRecepcionComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('cantidades_recibidas', models.TextField(help_text='JSON serializado: diccionario {producto_id: cantidad_recibida}')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recepcion', to='pedidos.pedidocolectivo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
