# Generated by Django 4.2.20 on 2025-04-12 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0016_notificacionrecepcioncomanda'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaCorreccionComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_propuesta', models.DateTimeField(auto_now_add=True)),
                ('cambios', models.TextField(help_text="JSON serializado: lista de cambios [{'socio_id': x, 'producto_id': y, 'cantidad': z}, ...]")),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validada', 'Validada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_correccion', to='pedidos.comandarecurrente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario_validador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_validadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
