# Generated by Django 4.2.20 on 2025-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_propuestacorreccioncomanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocolectivo',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('pendiente_validar', 'Pendiente de Validar'), ('inactivo', 'Inactivo')], default='abierto', max_length=20),
        ),
    ]
