# Generated by Django 4.2.20 on 2025-04-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_alter_pedidocolectivo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocolectivo',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('pendiente', 'Pendiente')], default='abierto', max_length=20),
        ),
    ]
