# Generated by Django 4.2.20 on 2025-04-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0021_alter_pedidocolectivo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocolectivo',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('pendiente', 'Pendiente'), ('cerrado', 'Cerrado'), ('inactivo', 'Inactivo')], default='abierto', max_length=20),
        ),
    ]
