# Generated by Django 4.2.20 on 2025-04-20 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socios', '0003_movimientocuenta_estado'),
        ('pedidos', '0026_alter_pedidocolectivo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacionstockconsumido',
            name='notas',
            field=models.TextField(blank=True, help_text='Descripción general de la recogida/grupo.', null=True),
        ),
        migrations.CreateModel(
            name='GestionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validado', 'Validado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones_stock_finalizadas', to=settings.AUTH_USER_MODEL)),
                ('gestor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones_stock_asignadas', to='socios.socio')),
            ],
            options={
                'verbose_name': 'Gestión de Stock',
                'verbose_name_plural': 'Gestiones de Stock',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='anotacionstockconsumido',
            name='gestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='pedidos.gestionstock'),
        ),
    ]
