# Generated by Django 4.2.20 on 2025-04-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0027_alter_anotacionstockconsumido_notas_gestionstock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotacionstockconsumido',
            name='gestion',
        ),
        migrations.AlterField(
            model_name='anotacionstockconsumido',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GestionStock',
        ),
    ]
