# Generated by Django 4.2.20 on 2025-04-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0028_remove_anotacionstockconsumido_gestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleccionsocio',
            name='estado_validacion_stock',
            field=models.CharField(choices=[('no_requerido', 'No Requerido'), ('pendiente', 'Pendiente de Validación'), ('validado', 'Validado'), ('modificado', 'Modificado por Stock'), ('rechazado', 'Rechazado por Stock')], default='no_requerido', max_length=20),
        ),
        migrations.AddField(
            model_name='seleccionsocio',
            name='notas_validacion_stock',
            field=models.TextField(blank=True, null=True),
        ),
    ]
