# Generated by Django 4.2.20 on 2025-04-20 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0029_seleccionsocio_estado_validacion_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaRevisionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_propuesta', models.DateTimeField(default=django.utils.timezone.now)),
                # Cambiar JSONField a TextField en la migración para compatibilidad con SQLite
                ('cambios_propuestos', models.TextField(help_text="Texto JSON: [{'producto_id': X, 'cantidad_propuesta': Y, 'cantidad_original': Z}, ...]")),
                ('notas_master', models.TextField(blank=True, help_text='Notas del Master al proponer la revisión.', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validada', 'Validada y Aplicada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('notas_validador', models.TextField(blank=True, help_text='Notas del Responsable de Stock al validar/rechazar.', null=True)),
                ('propuesto_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_propuestas', to=settings.AUTH_USER_MODEL)),
                ('seleccion_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_revision', to='pedidos.seleccionsocio')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_validadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propuesta de Revisión de Stock',
                'verbose_name_plural': 'Propuestas de Revisión de Stock',
                'ordering': ['-fecha_propuesta'],
            },
        ),
    ]
