# Generated by Django 4.2.20 on 2025-04-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0030_propuestarevisionstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuestarevisionstock',
            name='cambios_propuestos',
            field=models.TextField(help_text="Texto JSON: [{'producto_id': X, 'cantidad_propuesta': Y, 'cantidad_original': Z}, ...]"),
        ),
    ]
