# Generated by Django 4.2.20 on 2025-04-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0031_alter_propuestarevisionstock_cambios_propuestos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seleccionsocio',
            name='estado_validacion_stock',
        ),
        migrations.RemoveField(
            model_name='seleccionsocio',
            name='notas_validacion_stock',
        ),
        migrations.DeleteModel(
            name='PropuestaRevisionStock',
        ),
    ]
