# Generated by Django 4.2.20 on 2025-05-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0034_alter_pedidocolectivo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocolectivo',
            name='fecha_inicio_pedidos',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora a partir de la cual los socios pueden empezar a añadir productos a este pedido.', null=True),
        ),
    ]
