# Generated by Django 4.2.20 on 2025-05-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0035_pedidocolectivo_fecha_inicio_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocolectivo',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('pendiente', 'Pendiente'), ('listo_para_finalizar', 'Listo para Finalizar'), ('inactivo', 'Inactivo')], default='abierto', max_length=20),
        ),
    ]
