# Generated by Django 4.2.20 on 2025-05-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0036_alter_pedidocolectivo_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comandarecurrente',
            options={'permissions': [('puede_crear_comanda_esporadica', 'Puede crear comandas recurrentes esporádicas')]},
        ),
    ]
