# Generated by Django 4.2.20 on 2025-06-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0037_alter_comandarecurrente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comandarecurrente',
            options={'permissions': [('puede_crear_comanda_esporadica', 'Puede crear comandas recurrentes esporádicas')], 'verbose_name': 'Comanda Recurrent', 'verbose_name_plural': 'Comandes recurrents'},
        ),
        migrations.AlterModelOptions(
            name='detalleseleccion',
            options={'verbose_name': 'Detall de Selecció', 'verbose_name_plural': 'Detalls selecció'},
        ),
        migrations.AlterModelOptions(
            name='pedidocolectivo',
            options={'verbose_name': 'Comanda Col·lectiva', 'verbose_name_plural': 'Comandes colectives'},
        ),
        migrations.AlterModelOptions(
            name='propuestacorreccioncomanda',
            options={'verbose_name': 'Proposta de Correcció de Comanda', 'verbose_name_plural': 'Propostes de Correcció de Comandes'},
        ),
        migrations.AlterModelOptions(
            name='seleccionsocio',
            options={'verbose_name': 'Selecció de Soci', 'verbose_name_plural': 'Seleccions de Socis'},
        ),
    ]
