# Generated by Django 4.2.20 on 2025-06-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeriacategoria',
            options={'ordering': ['-fecha_creacion', 'nombre'], 'verbose_name': 'Categoría de galería', 'verbose_name_plural': 'Categories de galeria'},
        ),
        migrations.AlterModelOptions(
            name='galeriaimagen',
            options={'ordering': ['-fecha_subida', 'titulo'], 'verbose_name': 'Imagen de galería', 'verbose_name_plural': 'Imatges de galeria'},
        ),
    ]
