# Generated by Django 3.2.21 on 2025-04-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocuenta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado')], default='pendiente', max_length=10),
        ),
    ]
