# Generated by Django 4.2.20 on 2025-04-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_movimientocuenta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='responsable_stock',
            field=models.BooleanField(default=False),
        ),
    ]
