# Generated by Django 4.2.20 on 2025-04-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_socio_responsable_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='responsable_stock',
        ),
    ]
