# Generated by Django 4.2.20 on 2025-04-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_sesionrecogida_retiradasocio_itemretirado_and_more'),
        ('socios', '0005_remove_socio_responsable_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocuenta',
            name='retirada_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta', to='stock.retiradasocio', verbose_name='Retirada Origen'),
        ),
    ]
