# Generated by Django 4.2.7 on 2025-04-22 15:25

from django.db import migrations

def crear_grupos(apps, schema_editor):
    """Crea los grupos de roles necesarios para la gestión de stock y recogida."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Crear grupo Socio Gestor de Stock
    gestor_stock_group, created_gestor = Group.objects.get_or_create(name='Socio Gestor de Stock')
    if created_gestor:
        print("Grupo 'Socio Gestor de Stock' creado.")
        # Aquí podríamos asignar permisos específicos si fuera necesario en el futuro
        # Ejemplo:
        # can_validate_pickup = Permission.objects.get(codename='can_validate_pickup_session')
        # gestor_stock_group.permissions.add(can_validate_pickup)

    # Crear grupo Socio Responsable de Recogida
    responsable_recogida_group, created_responsable = Group.objects.get_or_create(name='Socio Responsable de Recogida')
    if created_responsable:
        print("Grupo 'Socio Responsable de Recogida' creado.")
        # Aquí podríamos asignar permisos específicos si fuera necesario en el futuro
        # Ejemplo:
        # can_register_pickup = Permission.objects.get(codename='can_register_pickup')
        # responsable_recogida_group.permissions.add(can_register_pickup)

class Migration(migrations.Migration):

    dependencies = [
        # Asegúrate de que la dependencia sea la migración anterior correcta
        ('socios', '0006_movimientocuenta_retirada_origen'),
        # Añadir dependencia de 'auth' si no está implícita por modelos anteriores
        # ('auth', '__latest__'), # O la migración específica de auth si es necesario
    ]

    operations = [
        migrations.RunPython(crear_grupos),
    ]
