# Generated by Django 4.2.20 on 2025-04-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0007_crear_grupos_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocuenta',
            name='retirada_origen',
        ),
    ]
