# Generated by Django 4.2.20 on 2025-04-22 15:53

from django.db import migrations
from django.contrib.auth.management import create_permissions

# Función para crear el grupo
def create_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Gestor de Stock')

# Función para eliminar el grupo (opcional, para revertir la migración)
def remove_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Gestor de Stock').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0008_remove_movimientocuenta_retirada_origen'),
        # Asegurarse de que los permisos de auth estén creados antes de intentar crear grupos
        ('auth', '__latest__'),
    ]

    operations = [
        migrations.RunPython(create_group, remove_group),
    ]
