# Generated by Django 4.2.20 on 2025-04-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0009_create_stock_manager_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='gestiona_stock',
            field=models.BooleanField(default=False, help_text='Marcar si este socio es el responsable de gestionar el stock.'),
        ),
    ]
