# Generated by Django 4.2.20 on 2025-04-25 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_proveedor_visible_en_web'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socios', '0010_socio_gestiona_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCompraSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad comprada (en unidades o kg/g según el producto)', max_digits=10)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_registradas', to='productos.producto')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_compra_realizados', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_registradas', to='socios.socio')),
            ],
            options={
                'verbose_name': 'Registro de Compra de Socio',
                'verbose_name_plural': 'Registros de Compras de Socios',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
