# Generated by Django 4.2.20 on 2025-04-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0011_registrocomprasocio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrocomprasocio',
            options={'ordering': ['estado', '-fecha_registro'], 'verbose_name': 'Registro de Compra de Socio', 'verbose_name_plural': 'Registros de Compras de Socios'},
        ),
        migrations.AddField(
            model_name='registrocomprasocio',
            name='costo_total_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo total calculado en el momento de la validación (cantidad * precio producto)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registrocomprasocio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('error', 'Error')], db_index=True, default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='registrocomprasocio',
            name='movimiento_cuenta',
            field=models.OneToOneField(blank=True, help_text='Movimiento en la cuenta del socio generado al validar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_compra_asociado', to='socios.movimientocuenta'),
        ),
    ]
