# Generated by Django 4.2.20 on 2025-04-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0012_alter_registrocomprasocio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocuenta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendent'), ('validado', 'Validado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='registrocomprasocio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendent'), ('validado', 'Validado'), ('error', 'Error')], db_index=True, default='pendiente', max_length=10),
        ),
    ]
