# Generated by Django 4.2.20 on 2025-05-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0014_alter_movimientocuenta_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='gestiona_productos',
            field=models.BooleanField(default=False, help_text='Marcar si este socio puede gestionar productos (añadir, editar, etc.).'),
        ),
    ]
