# Generated by Django 4.2.20 on 2025-05-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0015_socio_gestiona_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='puede_crear_comanda_esporadica',
            field=models.BooleanField(default=False, help_text='Marcar si este socio puede crear comandas esporádicas desde la intranet.'),
        ),
    ]
