# Generated by Django 4.2.20 on 2025-05-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0016_socio_puede_crear_comanda_esporadica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='puede_crear_comanda_esporadica',
        ),
    ]
