# Generated by Django 4.2.20 on 2025-05-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0017_remove_socio_puede_crear_comanda_esporadica'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='puede_crear_comandas_esporadicas',
            field=models.BooleanField(default=False, help_text='Marcar si este socio puede crear comandas recurrentes de tipo esporádico.'),
        ),
    ]
