# Generated by Django 4.2.20 on 2025-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0018_socio_puede_crear_comandas_esporadicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocuenta',
            name='descripcion',
            field=models.TextField(help_text='Poseu el vostre numero de uf'),
        ),
    ]
