# Generated by Django 4.2.20 on 2025-06-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0019_alter_movimientocuenta_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentasocio',
            options={'verbose_name': 'Cuenta de Socio', 'verbose_name_plural': 'Comptes de socis'},
        ),
        migrations.AlterModelOptions(
            name='movimientocuenta',
            options={'verbose_name': 'Movimiento de Cuenta', 'verbose_name_plural': 'Moviments de comptes'},
        ),
        migrations.AlterModelOptions(
            name='registrocomprasocio',
            options={'ordering': ['estado', '-fecha_registro'], 'verbose_name': 'Registro de Compra de Socio', 'verbose_name_plural': 'Registres de Compres de Socis'},
        ),
        migrations.AlterModelOptions(
            name='socio',
            options={'verbose_name': 'Socio', 'verbose_name_plural': 'Socis'},
        ),
    ]
