"""
Django settings for coopconsum project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Application definition

INSTALLED_APPS = [
    # Apps por defecto de Django amb ordre personalitzat
    'django.contrib.admin',
    'coopconsum.django_apps.CustomAuthConfig',  # Auth amb prefix per ordre
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'corsheaders',
    'adminlte3',
    'adminlte3_theme',
    # 'ckeditor',  # Temporalment comentat
    # Apps cooperativa amb verbose_name numerat per ordre:
    'socios.apps.SociosConfig',
    'web.apps.WebConfig',
    'pedidos.apps.PedidosConfig',
    'productos.apps.ProductosConfig',
    'stock.apps.StockConfig',
    'desitjos.apps.DesitjosConfig',
    'eventos.apps.EventosConfig',
    'api.apps.ApiConfig',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Añadir este middleware después de SessionMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'coopconsum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / "templates" ],  # Agrega esta línea
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pedidos.context_processors.pedidos_info_processor', # Actualizado para incluir más información de pedidos
                'stock.context_processors.registros_compra_pendientes_processor', # Añadido para registros de compra pendientes
                'web.context_processors.configuracio_web', # Configuració web dinàmica
            ],
        },
    },
]


WSGI_APPLICATION = 'coopconsum.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'coopconsum_db', # Nombre de tu base de datos PostgreSQL
        'USER': 'coopconsum_user', # Tu usuario de PostgreSQL
        'PASSWORD': 'your_password', # Tu contraseña de PostgreSQL
        'HOST': 'localhost', # O la IP de tu servidor de PostgreSQL
        'PORT': '5432', # Puerto por defecto de PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = '/socios/'    # A dónde se redirige después del login
LOGIN_URL = '/accounts/login/'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ca' # Cambiado a catalán

LANGUAGES = [
    ('ca', 'Català'),
    ('es', 'Español'),
]

TIME_ZONE = 'Europe/Madrid' # Ajustado a la zona horaria local (opcional pero recomendado)

USE_I18N = True

USE_TZ = True

FIRST_DAY_OF_WEEK = 1 # Lunes como primer día de la semana

# Locale paths for translations
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / "static", ]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise for serving static files in production
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# WhiteNoise per servir fitxers media en producció
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGOUT_REDIRECT_URL = '/' # Redirigir a la web pública després del logout

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # API pública para intercambio entre cooperativas
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # Interfície web interactiva per explorar l'API
    ],
}

# CORS Configuration - Permite intercambio entre cooperativas
CORS_ALLOW_ALL_ORIGINS = True  # Para desarrollo y cooperativas públicas
CORS_ALLOWED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",
]
CORS_ALLOW_METHODS = [
    'GET',
    'HEAD',
    'OPTIONS',
]

# CKEditor Configuration - Editor WYSIWYG per usuaris no tècnics
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['BulletedList', 'NumberedList'],
            ['Link', 'Unlink'],
            ['Format', 'RemoveFormat'],
            ['Source']  # Opció per veure codi HTML si cal
        ],
        'format_tags': 'p;h2;h3;h4',
        'height': 250,
        'width': '100%',
        'removeDialogTabs': 'image:advanced;link:advanced',  # Simplificar diàlegs
        'extraPlugins': '',
        'removePlugins': 'elementspath',  # Eliminar path de baix per netejar interfície
    },
    'minimal': {
        'toolbar': [
            ['Bold', 'Italic'],
            ['BulletedList'],
            ['RemoveFormat']
        ],
        'height': 150,
        'width': '100%',
    }
}