# Generated by Django 3.2.21 on 2025-03-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_stock',
            field=models.BooleanField(default=False, help_text='Marcar si este producto se gestiona como stock.'),
        ),
    ]
