# Generated by Django 3.2.21 on 2025-04-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_es_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_venta',
            field=models.CharField(choices=[('ud', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo')], default='ud', help_text='Unidad en la que se vende y se expresa el precio.', max_length=2),
        ),
    ]
