# Generated by Django 3.2.21 on 2025-04-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20250412_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='visible_en_web',
            field=models.BooleanField(default=True, help_text='Si está marcado, el proveedor aparecerá en la web.', verbose_name='Visible en la web'),
        ),
    ]
