# Generated by Django 4.2.20 on 2025-04-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_proveedor_visible_en_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='visible_en_inicio',
            field=models.BooleanField(default=False, help_text='Si está marcado, el proveedor aparecerá en la página de inicio.', verbose_name='Visible en la página de inicio'),
        ),
    ]
