# Generated by Django 4.2.20 on 2025-04-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_proveedor_visible_en_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado_en_inicio',
            field=models.BooleanField(default=False, help_text='Si está marcado, el producto aparecerá en la sección de productos destacados de la página de inicio.', verbose_name='Destacado en inicio'),
        ),
    ]
