# Generated by Django 4.2.20 on 2025-05-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_destacado_en_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_venta',
            field=models.CharField(choices=[('ud', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litre')], default='ud', help_text='Unidad en la que se vende y se expresa el precio.', max_length=2),
        ),
    ]
