# Generated by Django 4.2.20 on 2025-06-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_producto_unidad_venta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producte', 'verbose_name_plural': 'Productes'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveïdor', 'verbose_name_plural': 'Proveïdors'},
        ),
    ]
