# Generated by Django 4.2.20 on 2025-05-09 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0009_producto_destacado_en_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socios', '0017_remove_socio_puede_crear_comanda_esporadica'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaDeseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Títol de la Carta de Desig')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripció')),
                ('imagen_representativa', models.ImageField(blank=True, null=True, upload_to='desitjos_cartas/', verbose_name='Imatge Representativa (opcional)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Data Creació')),
                ('fecha_limite_interes', models.DateField(blank=True, null=True, verbose_name='Data Límit per Expressar Interès')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('minimo_alcanzado', 'Mínimo Alcanzado'), ('completada', 'Completada'), ('archivada', 'Archivada')], default='borrador', max_length=20, verbose_name='Estat de la Carta')),
                ('tipo_minimo', models.CharField(blank=True, choices=[('unidades_producto', 'Unidades totales de un producto específico'), ('socios_producto', 'Número de socios interesados en un producto específico'), ('importe_total', 'Importe total acumulado para la carta')], max_length=30, null=True, verbose_name='Tipus de Mínim Requerit')),
                ('valor_minimo_requerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor del Mínim Requerit')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartas_deseo_creadas_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Creada Per')),
                ('producto_objetivo_minimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartas_objetivo_minimo_productos', to='productos.producto', verbose_name='Producte Objectiu (si el mínim és per producte)')),
                ('productos', models.ManyToManyField(related_name='cartas_deseo_productos', to='productos.producto', verbose_name='Productes inclosos en aquesta carta')),
                ('proveedor_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.proveedor', verbose_name='Proveïdor Suggerit (opcional)')),
            ],
            options={
                'verbose_name': 'Carta de Desig',
                'verbose_name_plural': 'Cartes de Desitjos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='InteresSocioEnCarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_deseada', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantitat Desitjada')),
                ('fecha_registro_interes', models.DateTimeField(auto_now_add=True, verbose_name="Data de Registre de l'Interès")),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Darrera Modificació')),
                ('carta_deseo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses_socios', to='desitjos.cartadeseo', verbose_name='Carta de Desig Associada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producte Desitjat')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses_en_cartas_socio', to='socios.socio', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Interès de Soci en Carta',
                'verbose_name_plural': 'Interessos de Socis en Cartes',
                'ordering': ['carta_deseo', 'socio', '-fecha_registro_interes'],
                'unique_together': {('carta_deseo', 'socio', 'producto')},
            },
        ),
    ]
