# Generated by Django 4.2.20 on 2025-06-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desitjos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartadeseo',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Esborrany'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('minimo_alcanzado', 'Mínim Aconseguit'), ('completada', 'Completada'), ('archivada', 'Arxivada')], default='borrador', max_length=20, verbose_name='Estat de la Carta'),
        ),
    ]
