name: Django Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_coopconsum_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client libpq-dev gettext
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage psycopg2-binary
    
    - name: Verify test settings exist
      run: |
        ls -la coopconsum/settings_test.py
        echo "Using pre-configured settings_test.py file"
    
    - name: Set Django settings module
      run: echo "DJANGO_SETTINGS_MODULE=coopconsum.settings_test" >> $GITHUB_ENV
    
    - name: Run migrations
      run: |
        python manage.py migrate --verbosity=0
    
    - name: Run tests with coverage
      run: |
        coverage run --source='.' manage.py test --verbosity=2
        coverage report -m
        coverage xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Generate coverage percentage
      run: |
        COVERAGE=$(coverage report --format=total)
        echo "Coverage: $COVERAGE%"
        echo "COVERAGE_PERCENT=$COVERAGE" >> $GITHUB_ENV